server:
  port: 9000

spring:
  application:
    name: Server-Provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      #http://peer1:8080/eureka/,http://peer2:8081/eureka/