server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: XXX@163.com
    password: XXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true